

server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/matching_mate?useSSL=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root

  redis:
    host: 127.0.0.1
    port: 6379

  properties:
    hibernate:
      default_batch_fetch_size: 1000

  jwt:
    headar: Authorization
    secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
    token-validity-in-seconds: 86400

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true
    jackson:
      serialization:
        fail-on-empty-beans: false

  devtools:
    restart:
      enable: true

  mvc:
    pathmatch:
      matching_strategy: ant_path_matcher

    servlet:
      load-on-startup: 1

  output:
    ansi:
      enabled: always